//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class accounts_look_up
    {
        public int AccountClassID { get; set; }
        public string ClassDescription { get; set; }
        public string AccountclassCode { get; set; }
        public string code { get; set; }
    }
}
