//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACCOUNT()
        {
            this.log_accounts = new HashSet<log_accounts>();
        }
    
        public int AccID { get; set; }
        public Nullable<int> customerID { get; set; }
        public string classcode { get; set; }
        public Nullable<int> currency { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public Nullable<int> status { get; set; }
        public string branch { get; set; }
        public int MakerID { get; set; }
        public int CheckerID { get; set; }
        public long amount { get; set; }
        public string AccountNumber { get; set; }
        public string uniqueIdentifier { get; set; }
        public string Comment { get; set; }
        public string MakerName { get; set; }
        public string CheckerName { get; set; }
        public string CustomerName { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<log_accounts> log_accounts { get; set; }
    }
}
