//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class branches_look_up
    {
        public string ID { get; set; }
        public string flexCode { get; set; }
        public string branch { get; set; }
    }
}
