//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class currency_rate_log
    {
        public int ChangeID { get; set; }
        public int FromCurrencyID { get; set; }
        public int ToCurrencyID { get; set; }
        public int OldRate { get; set; }
        public int NewRate { get; set; }
    }
}
