//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class currency_rate_look_up
    {
        public int RateID { get; set; }
        public string FromCur { get; set; }
        public string ToCur { get; set; }
        public double Rate { get; set; }
    }
}
