//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUSTOMER()
        {
            this.ACCOUNTS = new HashSet<ACCOUNT>();
            this.USERS = new HashSet<USER>();
            this.log_customers = new HashSet<log_customers>();
        }
    
        public int custID { get; set; }
        public string Name { get; set; }
        public string CIF { get; set; }
        public string address { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public Nullable<int> age { get; set; }
        public string gender { get; set; }
        public System.DateTime datecreated { get; set; }
        public string MakerName { get; set; }
        public int MakerID { get; set; }
        public string CheckerName { get; set; }
        public Nullable<int> CheckerID { get; set; }
        public int status { get; set; }
        public string nationalID { get; set; }
        public string comments { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACCOUNT> ACCOUNTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER> USERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<log_customers> log_customers { get; set; }
    }
}
