//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_accounts
    {
        public int logID { get; set; }
        public int custID { get; set; }
        public int MakerID { get; set; }
        public int CheckerID { get; set; }
        public System.DateTime Date { get; set; }
        public string branchCode { get; set; }
        public int status { get; set; }
        public int AccID { get; set; }
        public string MakerName { get; set; }
        public string CheckerName { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
    }
}
