//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBE
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mini_bankEntities : DbContext
    {
        public mini_bankEntities()
            : base("name=mini_bankEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACCOUNT> ACCOUNTS { get; set; }
        public virtual DbSet<accounts_look_up> accounts_look_up { get; set; }
        public virtual DbSet<branches_look_up> branches_look_up { get; set; }
        public virtual DbSet<currency_look_up> currency_look_up { get; set; }
        public virtual DbSet<currency_rate_log> currency_rate_log { get; set; }
        public virtual DbSet<CUSTOMER> CUSTOMERS { get; set; }
        public virtual DbSet<log_accounts> log_accounts { get; set; }
        public virtual DbSet<log_customers> log_customers { get; set; }
        public virtual DbSet<Role_look_up> Role_look_up { get; set; }
        public virtual DbSet<status_look_up> status_look_up { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
        public virtual DbSet<currency_rate_look_up> currency_rate_look_up { get; set; }
    }
}
