//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class SingleSideTransactions_log
    {
        public int transactionID { get; set; }
        public string customerName { get; set; }
        public string AccountNumber { get; set; }
        public long amount { get; set; }
        public bool Deposite { get; set; }
        public System.DateTime dateCreated { get; set; }
    }
}
