//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transactions_log
    {
        public int transactionID { get; set; }
        public string senderName { get; set; }
        public int senderID { get; set; }
        public string recieverName { get; set; }
        public int recieverID { get; set; }
        public string srcAccountNumber { get; set; }
        public string distAccountNumber { get; set; }
        public string srcCurr { get; set; }
        public string distCurr { get; set; }
        public long amountInSrcCurr { get; set; }
        public long amountInDistCurr { get; set; }
        public double rateUsed { get; set; }
        public System.DateTime dateCreated { get; set; }
    }
}
