//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public int ID { get; set; }
        public string UserID { get; set; }
        public string Name { get; set; }
        public string password { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> Role { get; set; }
        public Nullable<bool> active { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
    }
}
