//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBE
{


    public partial class validateCustomer
    {

        /// <summary>
        /// CTRL_CheckerMenu1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NBE.Controls.CTRL_CheckerMenu CTRL_CheckerMenu1;

        /// <summary>
        /// CTRL_validateCustomer1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NBE.Controls.CTRL_validateCustomer CTRL_validateCustomer1;
    }
}
